app/src/Entity/Immatriculation.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ImmatriculationRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;


#[ORM\Entity(repositoryClass: ImmatriculationRepository::class)]
#[ORM\Table(name: '`immatriculations`')]
#[ORM\HasLifecycleCallbacks()]
#[ApiResource()]
class Immatriculation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 150, nullable: true, unique: true)]
    private ?string $reference;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $status;

    #[ORM\Column(type:"string", unique:true)]
    private ?string $numeroReferenceExterne;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $created_at;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $modified_at;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $type;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $code;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $payment_type;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $latitude;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $longitude;

    #[ORM\ManyToOne(inversedBy: 'immatriculations')]
    private ?User $agent = null;

    public function __construct()
    {
        $this->reference = Uuid::v4()->toRfc4122();
        $this->created_at = new DateTime();
        $this->modified_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeInterface|null $created_at
     * @return Immatriculation
     */
    public function setCreatedAt(?DateTimeInterface $created_at): Immatriculation
    {
        $this->created_at = $created_at;
        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    public function getPaymentType(): ?string
    {
        return $this->payment_type;
    }

    public function setPaymentType(?string $payment_type): void
    {
        $this->payment_type = $payment_type;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(?string $latitude): void
    {
        $this->latitude = $latitude;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): void
    {
        $this->longitude = $longitude;
    }

    public function getAgent(): ?User
    {
        return $this->agent;
    }

    public function setAgent(?User $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * @param string|null $code
     * @return Immatriculation
     */
    public function setCode(?string $code): Immatriculation
    {
        $this->code = $code;
        return $this;
    }



    /**
     * @return DateTimeInterface|null
     */
    public function getModifiedAt(): ?DateTimeInterface
    {
        return $this->modified_at;
    }

    /**
     * @param DateTimeInterface|null $modified_at
     * @return Immatriculation
     */
    public function setModifiedAt(?DateTimeInterface $modified_at): Immatriculation
    {
        $this->modified_at = $modified_at;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * @param string|null $reference
     * @return Immatriculation
     */
    public function setReference(?string $reference): Immatriculation
    {
        $this->reference = $reference;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getNumeroReferenceExterne(): ?string
    {
        return $this->numeroReferenceExterne;
    }

    /**
     * @param string|null $numeroReferenceExterne
     * @return Immatriculation
     */
    public function setNumeroReferenceExterne(?string $numeroReferenceExterne): Immatriculation
    {
        $this->numeroReferenceExterne = $numeroReferenceExterne;
        return $this;
    }


}

app/src/Form/ImmatriculationType.php
<?php

namespace App\Form;

use App\Entity\Immatriculation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImmatriculationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('status')
            ->add('created_at')
            ->add('updated_at')
            ->add('type')
            ->add('identification_id')
            ->add('payment_type')
            ->add('latitude')
            ->add('longitude')
            ->add('agent')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Immatriculation::class,
        ]);
    }
}

app/src/Controller/ImmatriculationController.php
<?php

namespace App\Controller;

use App\Entity\Immatriculation;
use App\Form\ImmatriculationType;
use App\Repository\ImmatriculationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/immatriculation')]
class ImmatriculationController extends AbstractController
{
    #[Route('/', name: 'app_immatriculation_index', methods: ['GET'])]
    public function index(ImmatriculationRepository $immatriculationRepository): Response
    {
        return $this->render('immatriculation/index.html.twig', [
            'immatriculations' => $immatriculationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_immatriculation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ImmatriculationRepository $immatriculationRepository): Response
    {
        $immatriculation = new Immatriculation();
        $form = $this->createForm(ImmatriculationType::class, $immatriculation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $immatriculationRepository->add($immatriculation, true);

            return $this->redirectToRoute('app_immatriculation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('immatriculation/new.html.twig', [
            'immatriculation' => $immatriculation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_immatriculation_show', methods: ['GET'])]
    public function show(Immatriculation $immatriculation): Response
    {
        return $this->render('immatriculation/show.html.twig', [
            'immatriculation' => $immatriculation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_immatriculation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Immatriculation $immatriculation, ImmatriculationRepository $immatriculationRepository): Response
    {
        $form = $this->createForm(ImmatriculationType::class, $immatriculation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $immatriculationRepository->add($immatriculation, true);

            return $this->redirectToRoute('app_immatriculation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('immatriculation/edit.html.twig', [
            'immatriculation' => $immatriculation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_immatriculation_delete', methods: ['POST'])]
    public function delete(Request $request, Immatriculation $immatriculation, ImmatriculationRepository $immatriculationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$immatriculation->getId(), $request->request->get('_token'))) {
            $immatriculationRepository->remove($immatriculation, true);
        }

        return $this->redirectToRoute('app_immatriculation_index', [], Response::HTTP_SEE_OTHER);
    }
}

app/templates/immatriculation/_delete_form.html.twig
<form method="post" action="{{ path('app_immatriculation_delete', {'id': immatriculation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ immatriculation.id) }}">
    <button class="btn">Delete</button>
</form>

app/templates/immatriculation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

app/templates/immatriculation/edit.html.twig
<!DOCTYPE html>

<title>Edit Immatriculation</title>

{% block body %}
    <h1>Edit Immatriculation</h1>

    {{ include('immatriculation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_immatriculation_index') }}">back to list</a>

    {{ include('immatriculation/_delete_form.html.twig') }}
{% endblock %}

app/templates/immatriculation/index.html.twig
<!DOCTYPE html>

<title>Immatriculation index</title>

{% block body %}
    <h1>Immatriculation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Status</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Type</th>
                <th>Identification_id</th>
                <th>Payment_type</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for immatriculation in immatriculations %}
            <tr>
                <td>{{ immatriculation.id }}</td>
                <td>{{ immatriculation.status }}</td>
                <td>{{ immatriculation.createdAt }}</td>
                <td>{{ immatriculation.updatedAt }}</td>
                <td>{{ immatriculation.type }}</td>
                <td>{{ immatriculation.identificationId }}</td>
                <td>{{ immatriculation.paymentType }}</td>
                <td>{{ immatriculation.latitude }}</td>
                <td>{{ immatriculation.longitude }}</td>
                <td>
                    <a href="{{ path('app_immatriculation_show', {'id': immatriculation.id}) }}">show</a>
                    <a href="{{ path('app_immatriculation_edit', {'id': immatriculation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_immatriculation_new') }}">Create new</a>
{% endblock %}

app/templates/immatriculation/new.html.twig
<!DOCTYPE html>

<title>New Immatriculation</title>

{% block body %}
    <h1>Create new Immatriculation</h1>

    {{ include('immatriculation/_form.html.twig') }}

    <a href="{{ path('app_immatriculation_index') }}">back to list</a>
{% endblock %}

app/templates/immatriculation/show.html.twig
<!DOCTYPE html>

<title>Immatriculation</title>

{% block body %}
    <h1>Immatriculation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ immatriculation.id }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ immatriculation.status }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ immatriculation.createdAt }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ immatriculation.updatedAt }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ immatriculation.type }}</td>
            </tr>
            <tr>
                <th>Identification_id</th>
                <td>{{ immatriculation.identificationId }}</td>
            </tr>
            <tr>
                <th>Payment_type</th>
                <td>{{ immatriculation.paymentType }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ immatriculation.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ immatriculation.longitude }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_immatriculation_index') }}">back to list</a>

    <a href="{{ path('app_immatriculation_edit', {'id': immatriculation.id}) }}">edit</a>

    {{ include('immatriculation/_delete_form.html.twig') }}
{% endblock %}